(function registerItems082To122(global) {
    'use strict';

    function unreviewedNotice() {
        return {
            type: 'note',
            html: `<p>This content was produced by gpt5.6sol and has not yet been reviewed; its correctness is not guaranteed.</p>`,
        };
    }

    global.GoogologyI18n.registerMessages('en', {
        items: {
            'item-082': {
                label: '\\({\\Gamma}_{0}\\)',
                detail: {
                    title: '\\({\\Gamma}_{0}\\)',
                    sections: [
                        {
                            type: 'html',
                            html: `<p>\\({\\Gamma}_{0}\\) is the least nonzero ordinal closed under the binary Veblen operation on smaller arguments. Under the finitary convention used here—leading zeroes may be omitted, while trailing zeroes may not—\\[{\\Gamma}_{0}=\\varphi(1,0,0).\\]</p><p>Equivalently, if \\(\\gamma_0=1\\) and \\(\\gamma_{n+1}=\\varphi_{\\gamma_n}(0)\\), then \\[{\\Gamma}_{0}=\\sup_{n\\lt{}\\omega}\\gamma_n.\\] It is commonly called the Feferman–Schütte ordinal.</p><p><strong>Convention and source:</strong> <a href="https://arxiv.org/abs/2205.11017">Bufetov, Nivasch, and Pakhomov, <cite>Generalized fusible numbers and their ordinals</cite>, §3.2</a>.</p>`,
                        },
                        unreviewedNotice(),
                    ],
                },
            },
            'item-083': {
                label: '\\({\\varphi}(1,0,1)\\)',
                detail: {
                    title: '\\({\\varphi}(1,0,1)\\)',
                    sections: [
                        {
                            type: 'html',
                            html: `<p>With the first two arguments fixed, \\(\\varphi(1,0,1)\\) is the next indexed value after \\(\\varphi(1,0,0)={\\Gamma}_{0}\\), obtained by changing the last argument from \\(0\\) to \\(1\\).</p><p>“Next” refers to the next index in this ternary Veblen family, not to the ordinal successor \\({\\Gamma}_{0}+1\\).</p><p><strong>Convention and source:</strong> <a href="https://arxiv.org/abs/2205.11017">Bufetov, Nivasch, and Pakhomov, <cite>Generalized fusible numbers and their ordinals</cite>, §3.2</a>.</p>`,
                        },
                        unreviewedNotice(),
                    ],
                },
            },
            'item-084': {
                label: '\\({\\varphi}(1,0,0,0)\\)',
                detail: {
                    title: '\\({\\varphi}(1,0,0,0)\\)',
                    sections: [
                        {
                            type: 'html',
                            html: `<p>\\(\\varphi(1,0,0,0)\\) is the first new closure point obtained when the ternary Veblen function is extended to four arguments. The additional trailing zero records a genuine increase in arity and therefore cannot be omitted.</p><p>Finitary Veblen functions are defined recursively by arity: an additional argument position enumerates common fixed points generated by lower arities and earlier argument values.</p><p><strong>Convention and source:</strong> <a href="https://arxiv.org/abs/2205.11017">Bufetov, Nivasch, and Pakhomov, <cite>Generalized fusible numbers and their ordinals</cite>, §3.2</a>.</p>`,
                        },
                        unreviewedNotice(),
                    ],
                },
            },
            'item-085': {
                label: 'SVO',
                detail: {
                    title: 'SVO',
                    sections: [
                        {
                            type: 'html',
                            html: `<p>SVO abbreviates small Veblen ordinal. It is the common closure bound of all finitary Veblen hierarchies: \\[\\mathrm{SVO}=\\sup\\{\\varphi(1,0),\\varphi(1,0,0),\\varphi(1,0,0,0),\\ldots\\}.\\]</p><p>Equivalently, it is the least ordinal not obtainable from \\(0\\) by repeatedly applying Veblen functions of arbitrary finite arity.</p><p><strong>Source:</strong> <a href="https://arxiv.org/abs/2205.11017">Bufetov, Nivasch, and Pakhomov, <cite>Generalized fusible numbers and their ordinals</cite>, §3.2</a>.</p>`,
                        },
                        unreviewedNotice(),
                    ],
                },
            },
            'item-086': {
                label: '\\(\\operatorname{tree}(n)\\)',
                detail: {
                    title: '\\(\\operatorname{tree}(n)\\)',
                    sections: [
                        {
                            type: 'html',
                            html: `<p>\\(\\operatorname{tree}(n)\\) is a weaker version of \\(\\operatorname{TREE}\\) in which the nodes have only one color. On a large-number scale, the two are very close.</p>`,
                        },
                    ],
                },
            },
            'item-087': {
                label: '\\(\\operatorname{TREE}(3)\\)',
                detail: {
                    title: '\\(\\operatorname{TREE}(3)\\)',
                    sections: [
                        {
                            type: 'html',
                            html: `<p><strong>Definition.</strong> Following Friedman, consider finite nonempty rooted trees whose vertices are labeled from \\(\\{1,2,3\\}\\). Siblings are unordered, and labels may repeat. \\(\\operatorname{TREE}(3)\\) is the greatest possible length \\(m\\) of a sequence \\(T_1,\\ldots,T_m\\) such that \\(T_i\\) has at most \\(i\\) vertices and, whenever \\(i\\lt{}j\\), there is no label-preserving, infimum-preserving homeomorphic embedding of \\(T_i\\) into \\(T_j\\). For rooted trees, preserving infima is equivalent to preserving lowest-common-ancestor relations: an edge may map to a path, but distinct source branches must enter distinct target branches.</p><p><strong>Why the exhaustive search terminates in theory.</strong> At position \\(i\\), there are only finitely many three-labeled rooted trees with at most \\(i\\) vertices, so all valid sequence prefixes form a finitely branching tree. If valid sequences existed at every length, König's lemma would give an infinite branch—an infinite bad sequence—contradicting Kruskal's tree theorem. The breadth-first search below must therefore reach an empty next level and return the greatest length. This establishes termination only in an idealized model with unbounded resources; it does not make the computation physically feasible.</p><p><strong>Formal sources:</strong> <a href="https://fomarchive.ugent.be/2006-March/010279.html">Harvey Friedman, “273: Sigma01/optimal/size”</a> gives the original definition of \\(\\operatorname{TREE}(k)\\); <a href="https://www.ams.org/tran/1960-095-02/S0002-9947-1960-0111704-1/S0002-9947-1960-0111704-1.pdf">J. B. Kruskal, “Well-quasi-ordering, the Tree Theorem, and Vázsonyi’s Conjecture” (1960)</a> is the original paper for the tree theorem used to prove termination.</p>`,
                        },
                        {
                            type: 'code',
                            language: 'python',
                            display: 'dialog',
                            title: 'Theoretical exhaustive search for three-label TREE',
                            openLabel: 'View the exhaustive-search program',
                            closeLabel: 'Close program',
                            source: `from functools import cache
from itertools import permutations, product


# A tree is represented canonically as:
#     (root_label, sorted_tuple_of_child_trees)
# Sorting the children makes sibling order irrelevant.

def valid_parent_array(parent):
    """Whether parent[1:] describes one rooted tree with root 0."""
    for start in range(1, len(parent)):
        seen = set()
        vertex = start

        while vertex != 0:
            if vertex in seen:
                return False
            seen.add(vertex)
            vertex = parent[vertex]

    return True


def canonical_tree(parent, labels):
    """Discard vertex names and return the canonical unordered tree."""
    children = [[] for _ in parent]

    for vertex in range(1, len(parent)):
        children[parent[vertex]].append(vertex)

    def build(vertex):
        return (
            labels[vertex],
            tuple(sorted(build(child) for child in children[vertex])),
        )

    return build(0)


@cache
def trees_of_size(number_of_labels, size):
    """Enumerate all nonempty unordered labeled rooted trees of this size."""
    result = set()

    # Vertex 0 is the root. Every other vertex chooses a parent.
    for tail in product(range(size), repeat=size - 1):
        parent = (-1,) + tail

        if not valid_parent_array(parent):
            continue

        # Labels are arbitrary and may repeat.
        for labels in product(range(number_of_labels), repeat=size):
            result.add(canonical_tree(parent, labels))

    return tuple(sorted(result))


@cache
def embeds(source, target):
    """Test label-preserving, infimum-preserving homeomorphic embedding."""
    source_label, source_children = source
    target_label, target_children = target

    # Dive: the source root is mapped below the target root.
    if any(embeds(source, child) for child in target_children):
        return True

    # Couple: match the two roots.
    if source_label != target_label:
        return False

    if len(source_children) > len(target_children):
        return False

    # Injectively assign source branches to target branches.
    return any(
        all(
            embeds(source_child, target_children[target_index])
            for source_child, target_index
            in zip(source_children, target_indices)
        )
        for target_indices in permutations(
            range(len(target_children)),
            len(source_children),
        )
    )


def TREE(number_of_labels):
    """Enumerate all bad sequences level by level and return TREE(k)."""
    if number_of_labels < 1:
        raise ValueError("number_of_labels must be positive")

    # frontier contains every valid sequence of length depth.
    frontier = {()}
    depth = 0

    while frontier:
        index = depth + 1

        # The tree at position index may have 1, ..., index vertices.
        candidates = tuple(
            tree
            for size in range(1, index + 1)
            for tree in trees_of_size(number_of_labels, size)
        )

        next_frontier = set()

        for sequence in frontier:
            for candidate in candidates:
                # Only an earlier-to-later embedding is forbidden.
                if all(
                    not embeds(earlier, candidate)
                    for earlier in sequence
                ):
                    next_frontier.add(sequence + (candidate,))

        # Length depth is possible, but length depth + 1 is not.
        if not next_frontier:
            return depth

        frontier = next_frontier
        depth += 1


assert TREE(1) == 1
assert TREE(2) == 3

print(TREE(3))`,
                        },
                        {
                            type: 'html',
                            html: `<p>\\(\\operatorname{TREE}(3)\\) lies slightly above the SVO level. HypCos has written further analyses of the \\(\\operatorname{tree}\\) function and \\(\\operatorname{TREE}(3)\\):</p><ul><li><a href="https://googology.fandom.com/wiki/User_blog:Hyp_cos/tree_function_and_TREE(3)">\\(\\operatorname{tree}\\) function and \\(\\operatorname{TREE}(3)\\)</a></li><li><a href="https://www.zhihu.com/question/667616017/answer/13389602444">Zhihu: Expressing Graham's number, \\(\\operatorname{TREE}(3)\\), and \\(\\operatorname{SCG}(13)\\) with BMS</a> (Chinese)</li><li><a href="https://www.zhihu.com/question/353941713/answer/885942447">Zhihu: Why are Graham's number and \\(\\operatorname{tree}(3)\\) so large?</a> (Chinese)</li></ul>`,
                        },
                        unreviewedNotice(),
                    ],
                },
            },
            'item-088': {
                label: '\\({\\varphi}({\\omega}@{\\omega})\\)',
                detail: {
                    title: '\\({\\varphi}({\\omega}@{\\omega})\\)',
                    sections: [
                        {
                            type: 'html',
                            html: `<p>The \\(\\operatorname{TREE}\\) function lies at this level. This is not a landmark position, however; there is nothing else here besides the \\(\\operatorname{TREE}\\) function.</p>`,
                        },
                    ],
                },
            },
            'item-089': {
                label: '\\(\\operatorname{TREE}(n)\\)',
                detail: {
                    title: 'The \\(\\operatorname{TREE}\\) function',
                    sections: [
                        {
                            type: 'html',
                            html: `<p>\\(\\operatorname{TREE}(1)=1\\) and \\(\\operatorname{TREE}(2)=3\\). Already at \\(\\operatorname{TREE}(3)\\), its value is far beyond the range that familiar large-number notations can convey intuitively.</p>`,
                        },
                    ],
                },
            },
            'item-090': {
                label: 'LVO',
                detail: {
                    title: 'LVO',
                    sections: [
                        {
                            type: 'html',
                            html: `<p>The large Veblen ordinal extends the Veblen construction to transfinite argument positions while requiring every expression to have finite support. It is the closure bound of these finite-support transfinitary Veblen operations, and is also called \\(E(0)\\), or the great Veblen number, in Veblen’s original framework.</p><p>Because this extension contains every finite-arity Veblen level, LVO lies above SVO.</p><p><strong>Source:</strong> <a href="https://doi.org/10.1090/S0002-9947-1908-1500814-9">Oswald Veblen, <cite>Continuous Increasing Functions of Finite and Transfinite Ordinals</cite> (1908)</a>.</p>`,
                        },
                        unreviewedNotice(),
                    ],
                },
            },
            'item-091': {
                label: '\\(\\mathrm{BHO}={\\psi}({\\Omega}_{2})\\)',
                detail: {
                    title: '\\(\\mathrm{BHO}={\\psi}({\\Omega}_{2})\\)',
                    sections: [
                        {
                            type: 'html',
                            html: `<p>The Bachmann–Howard ordinal is obtained by ordinal collapsing: auxiliary \\(\\Omega\\)-levels are introduced in the closure construction, and \\(\\psi\\) then collapses the resulting structure back to a countable ordinal. In the Buchholz convention used here, \\(\\psi\\) abbreviates \\(\\psi_0\\), and \\[\\mathrm{BHO}=\\psi_0(\\Omega_2).\\]</p><p>The auxiliary \\(\\Omega_n\\) symbols act as scaffolding for the recursive closure; the value returned by \\(\\psi_0\\) is countable.</p><p><strong>Source:</strong> <a href="https://doi.org/10.1016/0168-0072(86)90052-7">Wilfried Buchholz, <cite>A new system of proof-theoretic ordinal functions</cite> (1986)</a> (<a href="https://epub.ub.uni-muenchen.de/3841/1/3841.pdf">open PDF</a>).</p>`,
                        },
                        unreviewedNotice(),
                    ],
                },
            },
            'item-092': {
                label: '\\(\\mathrm{BO}={\\psi}({\\Omega}_{{\\omega}})\\)',
                detail: {
                    title: 'Buchholz ordinal (\\(\\mathrm{BO}={\\psi}({\\Omega}_{{\\omega}})\\))',
                    sections: [
                        {
                            type: 'html',
                            html: `<p><strong>BMS representation:</strong> \\((0,0,0)(1,1,1)=(0,0)(1,1)(2,2)(3,3)\\ldots\\)</p><p>Under the same Buchholz convention, let \\[\\Omega_\\omega=\\sup_{1\\leq n\\lt{}\\omega}\\Omega_n.\\] The ordinal called the Buchholz ordinal here is \\[\\mathrm{BO}:=\\psi_0(\\Omega_\\omega)=\\sup_{1\\leq n\\lt{}\\omega}\\psi_0(\\Omega_n).\\] Thus it is the countable limit of the finite \\(\\Omega_n\\)-collapse levels. As above, the shorter \\(\\psi\\) in the item label denotes \\(\\psi_0\\), while the subscript in \\(\\Omega_\\omega\\) is part of the hierarchy and is not an exponent.</p><p><strong>Source:</strong> <a href="https://doi.org/10.1016/0168-0072(86)90052-7">Wilfried Buchholz, <cite>A new system of proof-theoretic ordinal functions</cite> (1986)</a> (<a href="https://epub.ub.uni-muenchen.de/3841/1/3841.pdf">open PDF</a>).</p>`,
                        },
                        unreviewedNotice(),
                    ],
                },
            },
            'item-093': {
                label: '\\(\\mathrm{BMS}:(0,0,0)(1,1,1)\\)',
            },
            'item-094': {
                label: '\\(\\mathrm{TFB}={\\psi}({\\Omega}_{{\\omega}+1})\\)',
                detail: {
                    title: '\\(\\mathrm{TFB}={\\psi}({\\Omega}_{{\\omega}+1})\\)',
                    sections: [
                        {
                            type: 'html',
                            html: `<p>It may also be written as \\({\\psi}({\\varepsilon}_{{\\Omega}_{{\\omega}}+1})\\). Here TFB denotes the limit of the Buchholz hydra.</p>`,
                        },
                    ],
                },
            },
            'item-095': {
                label: 'EBO',
                detail: {
                    title: 'EBO (Extended Buchholz ordinal)',
                    sections: [
                        {
                            type: 'html',
                            html: `<p><strong>BMS representation:</strong> \\((0,0,0)(1,1,1)(2,1,1)(3,1,0)(2,0,0)\\)</p><p>Here EBO denotes the limit of the <a href="https://googology.fandom.com/wiki/Extended_Buchholz's_function">Extended Buchholz's function</a>.</p>`,
                        },
                    ],
                },
            },
            'item-096': {
                label: '\\(\\mathrm{BMS}:(0,0,0)(1,1,1)(2,1,1)(3,1,0)(2,0,0)\\)',
            },
            'item-097': {
                label: 'SSO',
                detail: {
                    title: 'SSO (Small Stegert ordinal; informal name)',
                    sections: [
                        {
                            type: 'html',
                            html: `<p><strong>BMS representation:</strong> \\((0,0,0)(1,1,1)(2,2,0)\\)</p><p>SSO is the common informal name used here, but the same abbreviation sometimes denotes other ordinals. For an unambiguous reference, use the BMS expression above.</p>`,
                        },
                    ],
                },
            },
            'item-098': {
                label: '\\(\\mathrm{BMS}:(0,0,0)(1,1,1)(2,2,0)\\)',
            },
            'item-099': {
                label: 'LRO',
                detail: {
                    title: 'LRO (Large Rathjen ordinal; informal name)',
                    sections: [
                        {
                            type: 'html',
                            html: `<p><strong>BMS representation:</strong> \\((0,0,0)(1,1,1)(2,2,2)\\)</p><p>LRO is the common informal name used here, but the same abbreviation sometimes denotes other ordinals. For an unambiguous reference, use the BMS expression above.</p>`,
                        },
                    ],
                },
            },
            'item-100': {
                label: '\\(\\mathrm{BMS}:(0,0,0)(1,1,1)(2,2,2)\\)',
            },
            'item-101': {
                label: 'Three-row BMS',
                detail: {
                    title: 'Three-row BMS',
                    sections: [
                        {
                            type: 'html',
                            html: `<p>Here “three-row” means that every column of a BMS matrix contains three natural-number entries. In this page’s scale layout, this item marks the upper end of the three-row BMS region; the following four-entry columns \\((0,0,0,0)(1,1,1,1)\\) begin the four-row region. The item therefore serves as the transition between the two row-count levels.</p>`,
                        },
                        unreviewedNotice(),
                    ],
                },
            },
            'item-102': {
                label: '\\(\\mathrm{BMS}:(0,0,0,0)(1,1,1,1)\\)',
            },
            'item-103': {
                label: 'SHO',
                detail: {
                    title: 'SHO: the limit of BMS',
                    sections: [
                        {
                            type: 'html',
                            html: `<p>“SHO” (Small Hydra Ordinal) is commonly used for the limit of the <a href="https://googology.fandom.com/wiki/Bashicu_matrix_system">Bashicu Matrix System (BMS)</a>.</p><p>Note: the name “Small Hydra Ordinal” would actually be more suitable for \\({\\varepsilon}_{0}\\), since \\({\\varepsilon}_{0}\\) corresponds to the simplest hydra, whereas the connection between BMS and hydras is not obvious. For reasons that are unclear, however, “SHO” came by a twist of fate to denote the limit of BMS, and the googology community is now accustomed to this name.</p>`,
                        },
                    ],
                },
            },
            'item-104': {
                label: '\\(\\mathrm{BMS}:(0,0,0,\\ldots)(1,1,1,\\ldots)\\)',
            },
            'item-105': {
                label: '\\(Y:(1,3)\\)',
            },
            'item-106': {
                label: '\\(\\operatorname{SCG}(n)\\)',
                detail: {
                    title: 'The \\(\\operatorname{SCG}\\) function',
                    sections: [
                        {
                            type: 'html',
                            html: `<p>A finite undirected graph is subcubic when every vertex has degree at most \\(3\\). SSCG uses simple subcubic graphs, with no loops or parallel edges; SCG allows loops and parallel edges. Neither definition requires connectedness.</p><p><strong>Definition.</strong> Fix \\(k\\in\\mathbb N\\). Consider sequences \\(G_1,\\ldots,G_N\\) such that \\(|V(G_i)|\\leq i+k\\), with no \\(i\\lt j\\) for which \\(G_i\\) is homeomorphically embeddable in \\(G_j\\). Equivalently, a subdivision of \\(G_i\\) must occur as a subgraph of \\(G_j\\). The greatest possible \\(N\\) is \\(\\operatorname{SCG}(k)\\); restricting all graphs to be simple gives \\(\\operatorname{SSCG}(k)\\). Hence \\[\\operatorname{SCG}(k)\\geq\\operatorname{SSCG}(k).\\]</p><p>Finite subcubic graphs are well-quasi-ordered by homeomorphic embeddability, so an infinite bad sequence cannot exist. For each vertex bound there are only finitely many isomorphism types; applying König's lemma to the finitely branching tree of bad sequences therefore gives a finite maximum for every \\(k\\).</p><p>Friedman proved that \\(\\operatorname{SSCG}(13)\\) exceeds the halting time of every blank-tape Turing machine whose termination has a proof in \\(\\Pi^1_1\\text{-}\\mathrm{CA}_0\\) using at most \\(2^{[2000]}\\) symbols, where \\(2^{[r]}\\) denotes a tower of \\(2\\)s of height \\(r\\). He later removed the simplicity restriction and restated the result for \\(\\operatorname{SCG}(13)\\), noting that \\(\\operatorname{TREE}(3)\\) is negligible by comparison.</p><p><strong>Sources:</strong> <a href="https://fomarchive.ugent.be/2006-April/010305.html">Harvey M. Friedman, FOM #274, <cite>Subcubic Graph Numbers</cite></a>; <a href="https://fomarchive.ugent.be/2006-April/010362.html">Harvey M. Friedman, FOM #279, <cite>Subcubic Graph Numbers/restated</cite></a>; <a href="https://doi.org/10.1090/conm/065/891251">Friedman, Robertson, and Seymour, <cite>The Metamathematics of the Graph Minor Theorem</cite></a>.</p>`,
                        },
                        unreviewedNotice(),
                    ],
                },
            },
            'item-107': {
                label: '\\(Y:(1,4)\\)',
                detail: {
                    title: '\\(Y:(1,4)\\)',
                    sections: [
                        {
                            type: 'html',
                            html: `<p>This is the graveyard of the various extensions of BMS.</p>`,
                        },
                    ],
                },
            },
            'item-108': {
                label: 'Limit of Y sequences',
                detail: {
                    title: 'Limit of Y sequences',
                    sections: [
                        {
                            type: 'html',
                            html: `<p>Y sequences are a notation for ordinals introduced by Yukito and based on finite differences of sequences. This item marks the limit of that notation.</p>`,
                        },
                    ],
                },
            },
            'item-109': {
                label: 'Limit of \\({\\omega}-Y\\) sequences',
                detail: {
                    title: 'Limit of \\({\\omega}-Y\\) sequences',
                    sections: [
                        {
                            type: 'html',
                            html: `<p>The \\({\\omega}-Y\\) sequence notation is a further extension of Y sequences. This item marks the limit of that extension.</p>`,
                        },
                    ],
                },
            },
            'item-110': {
                label: 'Grand proposals for various extensions of Y sequences',
                detail: {
                    title: 'Grand proposals for various extensions of Y sequences',
                    sections: [
                        {
                            type: 'html',
                            html: `<p>Few of these extensions currently have rigorous definitions.</p>`,
                        },
                    ],
                },
            },
            'item-111': {
                label: 'Limit of iBLP',
                detail: {
                    title: 'Limit of iBLP',
                    sections: [
                        {
                            type: 'html',
                            html: `<p>iBLP stands for Infinite Basic Laver Patterns, introduced by @test_alpha0. This item marks the limit of that system.</p><p>In @test_alpha0's formal definition, a basic Laver pattern (BLP) is a finite combinatorial object \\(p=(s,\\ell)\\): \\(s\\) consists of finitely many strictly increasing sequences of natural numbers, called rows, and \\(\\ell\\) records the step length of each row. These data encode combinatorial relations among critical points of elementary embeddings.</p><p><strong>Source:</strong> <a href="https://arxiv.org/abs/2501.06733v5">@test_alpha0, <cite>Notes on Laver Tables</cite>, Definition 2.6</a>.</p>`,
                        },
                        unreviewedNotice(),
                    ],
                },
            },
            'item-112': {
                label: 'Laver Table \\(q(5)\\)',
                detail: {
                    title: 'Laver Table \\(q(5)\\)',
                    sections: [
                        {
                            type: 'html',
                            html: `<p><strong>Lower bounds.</strong> Basic Laver patterns (BLPs), introduced by @test_alpha0, give a very small lower bound for \\(q(5)\\). The cited paper rigorously proves that the bound derived from this BLP exceeds \\(\\varepsilon_0\\)-level large numbers.</p><p>Further analyses of BLPs and iBLPs in the large-number community place them far beyond BMS and even beyond the \\(\\omega\\)-Y-sequence level.</p><p><strong>Source:</strong> <a href="https://arxiv.org/abs/2501.06733v5">@test_alpha0, <cite>Notes on Laver Tables</cite> (results on Basic Laver Patterns)</a>.</p>`,
                        },
                        unreviewedNotice(),
                    ],
                },
            },
            'item-113': {
                label: 'Laver Table',
                detail: {
                    title: 'Laver Table',
                    sections: [
                        {
                            type: 'html',
                            html: `<p>Laver Tables are a special class of finite algebraic structures studied in set theory. The underlying set of the \\(n\\)-th Laver Table \\(A_n\\) is \\(\\{1,\\ldots,2^n\\}\\), and its operation is uniquely determined by the recursion\\[2^n\\star_n b=b,\\qquad a\\star_n1=a+1,\\]\\[a\\star_n(b+1)=(a\\star_n b)\\star_n(a+1)\\qquad(a,b\\lt{}2^n).\\]This operation satisfies left self-distributivity: \\[a\\star_n(b\\star_n c)=(a\\star_n b)\\star_n(a\\star_n c).\\]</p><p>For every \\(a\\), the sequence \\(a\\star_n1,a\\star_n2,\\ldots\\) repeats periodically. Its least period is a power of \\(2\\); the values within one period are strictly increasing and end at \\(2^n\\). The natural reduction modulo \\(2^n\\) from \\(A_{n+1}\\) to \\(A_n\\) is a homomorphism.</p><p>Let \\(\\pi_k(1)\\) be the least period of the first row of \\(A_k\\), and define\\[q(n)=\\min\\{k\\in\\mathbb N\\mid\\pi_k(1)=2^n\\}.\\]Thus \\(q(n)\\) is the least table index at which the first-row period becomes \\(2^n\\); the corresponding algebra \\(A_{q(n)}\\) has order \\(2^{q(n)}\\). The program below constructs complete Laver Tables for \\(k=0,1,2,\\ldots\\) and checks their first rows. It verifies \\(q(0),\\ldots,q(4)=(0,2,3,5,9)\\) and, when time and memory costs are ignored, gives an exhaustive computation of general \\(q(n)\\).</p><p><strong>Sources:</strong> <a href="https://arxiv.org/abs/math/9503204">Randall Dougherty, <cite>Critical points in an algebra of elementary embeddings, II</cite>, §2 and Proposition 2.5</a>; <a href="https://arxiv.org/abs/1810.00548">Philippe Biane, <cite>Laver tables and combinatorics</cite>, §§2–3 and §7.2</a>.</p>`,
                        },
                        {
                            type: 'code',
                            language: 'python',
                            display: 'dialog',
                            title: 'Exhaustively compute Laver-Table \\(q(n)\\)',
                            openLabel: 'View the \\(q(n)\\) search',
                            closeLabel: 'Close program',
                            source: `def laver_table(k):
    """Construct the complete k-th Laver Table from its recursion."""
    size = 1 << k
    table = [[0] * (size + 1) for _ in range(size + 1)]

    # The last row satisfies 2^k ⋆ b = b.
    for b in range(1, size + 1):
        table[size][b] = b

    # Every row needed on the right has index greater than a,
    # so it has already been constructed.
    for a in range(size - 1, 0, -1):
        table[a][1] = a + 1
        for b in range(1, size):
            table[a][b + 1] = table[table[a][b]][a + 1]

    return table


def first_row_period(k):
    """Return the least period of the first row of A_k."""
    table = laver_table(k)
    size = 1 << k

    # One period increases strictly and first reaches 2^k at its end.
    return next(
        period
        for period in range(1, size + 1)
        if table[1][period] == size
    )


def q(n):
    """Find the least table index whose first-row period is 2^n."""
    if n < 0:
        raise ValueError("n must be a nonnegative integer")

    target_period = 1 << n
    k = 0

    while first_row_period(k) != target_period:
        k += 1

    return k


assert [q(n) for n in range(5)] == [0, 2, 3, 5, 9]

requested_n = int(input("n = "))
print(f"q({requested_n}) = {q(requested_n)}")`,
                        },
                        unreviewedNotice(),
                    ],
                },
            },
            'item-114': {
                label: 'LTY',
                detail: {
                    title: 'LTY (Laver table yarn)',
                    sections: [
                        {
                            type: 'html',
                            html: `<p>LTY stands for “Laver table yarn,” also called “Luo Tianyi” (洛天依), and was introduced by @test_alpha0.</p><p>Given a computable increasing sequence of elementary embeddings \\(\\vec j=(j_1,j_2,\\ldots)\\), let \\(\\gamma_{i,i'}\\) be the \\(i'\\)-th critical point generated by \\(j_i\\). @test_alpha0's Definition 4.5 defines a well-preorder \\(LTY_{\\vec j}\\) on pairs of integers by\\[(i_1,i'_1)\\leq(i_2,i'_2)\\quad\\Longleftrightarrow\\quad\\gamma_{i_1,i'_1}\\leq\\gamma_{i_2,i'_2}.\\]The “yarn” interweaves the critical-point sequences associated with different embeddings into one ordering. For computable \\(\\vec j\\), the order type of the corresponding union of critical points is also computable.</p><p><strong>Source:</strong> <a href="https://arxiv.org/abs/2501.06733v5">@test_alpha0, <cite>Notes on Laver Tables</cite>, Definitions 4.2 and 4.5 and Theorem 4.3</a>.</p>`,
                        },
                        unreviewedNotice(),
                    ],
                },
            },
            'item-115': {
                label: '\\(\\operatorname{PTO}(Z_{3})\\)',
                detail: {
                    title: '\\(\\operatorname{PTO}(Z_{3})\\)',
                    sections: [
                        {
                            type: 'html',
                            html: `<p>\\(\\operatorname{PTO}(Z_{2})\\) is greater than or equal to the limit of BMS, and \\(\\operatorname{PTO}(Z_{3})\\) may be somewhat larger still.</p>`,
                        },
                    ],
                },
            },
            'item-116': {
                label: '\\(\\operatorname{PTO}(Z_{{\\omega}})\\)',
                detail: {
                    title: '\\(\\operatorname{PTO}(Z_{{\\omega}})\\)',
                    sections: [
                        {
                            type: 'html',
                            html: `<p>A higher-level proof-theoretic ordinal.</p>`,
                        },
                    ],
                },
            },
            'item-117': {
                label: `Loader's number`,
                detail: {
                    title: `Loader's number`,
                    sections: [
                        {
                            type: 'html',
                            html: `<p>Loader's number is an enormous integer generated by a program. Its generating logic is very simple, but the resulting value is extraordinarily large.</p>`,
                        },
                    ],
                },
            },
            'item-118': {
                label: '\\(\\operatorname{PTO}(\\mathrm{ZFC})\\)',
                detail: {
                    title: '\\(\\operatorname{PTO}(\\mathrm{ZFC})\\)',
                    sections: [
                        {
                            type: 'html',
                            html: `<p>The proof-theoretic ordinal of ZFC, the standard axiomatic system of modern mathematics.</p>`,
                        },
                    ],
                },
            },
            'item-119': {
                label: '\\(\\operatorname{PTO}(\\mathrm{ZFC}+I_{0})\\)',
                detail: {
                    title: '\\(\\operatorname{PTO}(\\mathrm{ZFC}+I_{0})\\)',
                    sections: [
                        {
                            type: 'html',
                            html: `<p>The proof-theoretic ordinal of ZFC augmented with the large-cardinal axiom \\(I_{0}\\).</p>`,
                        },
                    ],
                },
            },
            'item-120': {
                label: `Harvey Friedman's undefined items`,
                detail: {
                    title: `Harvey Friedman's undefined items`,
                    sections: [
                        {
                            type: 'html',
                            html: `<p>This great mathematician has introduced many extremely fast-growing concepts that googologists have not yet fully digested.</p>`,
                        },
                    ],
                },
            },
            'item-121': {
                label: '\\(\\operatorname{BB}(n)\\)',
                detail: {
                    title: 'The Busy Beaver function',
                    sections: [
                        {
                            type: 'html',
                            html: `<p>\\(\\operatorname{BB}(n)\\) is defined as the largest number of symbols that a Turing machine with \\(n\\) states can print before halting. It is a typical uncomputable function, and its growth rate far exceeds that of any computable ordinal system.</p>`,
                        },
                    ],
                },
            },
            'item-122': {
                label: '\\(\\operatorname{Rayo}(n)\\)',
                detail: {
                    title: `Rayo's number`,
                    sections: [
                        {
                            type: 'html',
                            html: `
                                <p>\\(\\operatorname{Rayo}(n)\\) is the least natural number greater than every natural number that can be uniquely specified by a formula of first-order set theory containing fewer than \\(n\\) symbols.</p>
                                <p>“Uniquely specified” is formalized through the satisfaction relation \\(\\operatorname{Sat}\\), which is itself defined in second-order set theory. The construction therefore uses second-order set theory to describe the semantics of first-order set-theory formulas; it does not use the language of second-order arithmetic.</p>
                                <p>The 2007 Big Number Duel used \\(n=10^{100}\\); \\(\\operatorname{Rayo}(10^{100})\\) is commonly called Rayo's number.</p>
                            `,
                        },
                    ],
                },
            },
        },
    });
})(globalThis);
